# Generated by Django 5.0.4 on 2024-09-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='avata',
            field=models.ImageField(blank=True, null=True, upload_to='avata/%Y/%m'),
        ),
    ]
